export const Msg = {
  GET_SUCCESS: '获取成功',
  GET_FAIL: '获取失败',
  LOGIN_SUCCESS: '登录成功',
  LOGIN_FAIL: '登录失败',
  VALIDATE_SUCCESS: '验证成功',
  VALIDATE_FAIL: '验证失败',
  PASSWORD_ERROR: '密码错误',
  CODE_ERROR: '验证码错误',
  SEND_SUCCESS: '发送成功',
  SEMD_FAIL: '发送失败',
  CREATE_SUCCESS: '创建成功',
  CREATE_FAIL: '创建失败',
  UPDATE_SUCCESS: '更新成功',
  UPDATE_FAIL: '更新失败',
  DELETE_SUCCESS: '删除成功',
  DELETE_FAIL: '删除失败',
  DATA_EXIST: '数据已存在',
  DATA_NOEXIST: '数据不存在',
  CONNECT_SUCCESS: '连接成功',
  CONNECT_FAIL: '连接失败',
  DISCONNECT_SUCCESS: '断开连接',
  UPLOAD_SUCCESS: '上传成功',
  UPLOAD_FAIL: '上传失败',
};
